Repository pulp/pulp-operator, pull requests merged in 2022-08, with the labels that each got.

#497 Prow test
  .ci/prow/openshift-test.sh
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml
  playbooks/pulp.yml
  roles/common/tasks/main.yml
  roles/pulp-routes/tasks/load_routes.yml
  roles/pulp-routes/tasks/main.yml
Labels: lgtm, approved

#503 Speed up galaxy tests
  .ci/scripts/galaxy_ng-tests.sh
Labels: lgtm, approved

#504 Use built catalog
  .ci/prow/openshift-test.sh
  Makefile
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#507 Improve API waiting on OCP test
  .ci/prow/openshift-test.sh
Labels: lgtm, approved

#508 Temporarily disable OCP test
  .ci/prow/openshift-test.sh
Labels: lgtm, approved

#509 Enable OCP test
  .ci/prow/openshift-test.sh
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml
Labels: lgtm, approved

#510 Verify request to route
  .ci/prow/openshift-test.sh
Labels: lgtm, approved

#511 Fix backup CI script
  .ci/scripts/backup_and_restore.sh
Labels: lgtm, approved

#512 Enable minio test
  .ci/assets/kubernetes/pulp-object-storage.aws.secret.yaml
  .ci/scripts/backup_and_restore.sh
  .ci/scripts/prepare-object-storage.sh
  .github/workflows/ci.yml
  .github/workflows/pr.yml
  .gitleaks.toml
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.s3.ci.yaml
  roles/pulp-api/defaults/main.yml
  roles/pulp-api/tasks/main.yml
  roles/pulp-api/tasks/s3-storage-configuration.yml
  roles/pulp-api/templates/pulp-api.deployment.yaml.j2
  roles/pulp-web/templates/pulp-web.deployment.yaml.j2
  up.sh
Labels: lgtm, approved

#519 Adding OLM descriptors
  api/v1alpha1/pulp_types.go
  api/v1alpha1/pulpbackup_types.go
  api/v1alpha1/pulprestore_types.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved, go-beta

#524 Bump manager limit to match AWX
  config/manager/manager.yaml
Labels: approved

#523 Improve OCP UI + update operator-sdk
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  config/testing/kustomization.yaml
  molecule/default/kustomize.yml
Labels: lgtm, approved

#527 Add commented LDAP settings to Pulp CR example
  config/samples/pulpproject_v1beta1_pulp_cr.default.yaml
Labels: approved

#528 Adding catalog example
  .ci/assets/kubernetes/catalog.yaml
  .github/workflows/ci.yml
Labels: lgtm, approved

#529 Update gitleaks
  .gitignore
  .gitleaks.toml
Labels: lgtm, approved

#530 Add content_path_prefix
  api/v1alpha1/pulp_types.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  controllers/pulp/route.go
Labels: lgtm, approved, go-beta

#532 Changing PulpSettings structure
  api/v1alpha1/pulp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  config/samples/galaxy.s3.ci.yaml
  config/samples/simple-sso.yaml
  config/samples/simple.yaml
  controllers/pulp/api.go
  controllers/pulp/common.go
  controllers/pulp/route.go
  controllers/pulp/web.go
Labels: lgtm, approved, go-beta

#533 Raise error when multiple object storages
  controllers/pulp/controller.go
Labels: lgtm, approved, go-beta

#535 CI: Run operator locally
  .ci/scripts/backup_and_restore.sh
  .ci/scripts/local.sh
  .github/workflows/ci.yml
  .github/workflows/scripts/show_logs.sh
  Makefile
  config/local/kustomization.yaml
  config/local/namespace.yaml
Labels: lgtm, approved, go-beta

#542 Pre-seed redhat-operators-pull-secret
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/pulp/controller.go
Labels: lgtm, approved, go-beta

#545 Use relatedImages to make disconnected deployments possible
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/samples/simple-external-db.yaml
  config/samples/simple-sso.yaml
  config/samples/simple.yaml
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/controller.go
  controllers/pulp/controller_test.go
  controllers/pulp/database.go
  controllers/pulp/redis.go
  controllers/pulp/web.go
  controllers/pulp/worker.go
Labels: lgtm, approved, go-beta

#547 Add operator events
  config/rbac/role.yaml
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/controller.go
  controllers/pulp/database.go
  controllers/pulp/redis.go
  controllers/pulp/route.go
  controllers/pulp/status.go
  controllers/pulp/web.go
  controllers/pulp/worker.go
Labels: lgtm, approved
