Repository pulp/pulp-operator, pull requests merged in 2022-10, with the labels that each got.

#655 Notify that project is still in alpha stage
  README.md
Labels: lgtm, approved

#656 Update container docs
  docs/container.md
Labels: lgtm, approved

#659 Remove link to redmine
  README.md
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#661 Make the operator namespace-scoped
  CHANGES/657.feature
  Makefile
  bundle/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  controllers/backup/controller.go
  controllers/pulp/controller.go
  controllers/restore/controller.go
  main.go
Labels: lgtm, approved

#663 Redis Form updates
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#665 Syntax fix for specifying redis deployment strategy default as recreate
  roles/pulp-api/templates/pulp-api.deployment.yaml.j2
  roles/pulp-content/templates/pulp-content.deployment.yaml.j2
  roles/pulp-web/templates/pulp-web.deployment.yaml.j2
  roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
  roles/redis/defaults/main.yml
  roles/redis/templates/redis.deployment.yaml.j2
Labels: lgtm, approved

#670 Fix strategy
  roles/pulp-api/templates/pulp-api.deployment.yaml.j2
  roles/pulp-content/templates/pulp-content.deployment.yaml.j2
  roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
  roles/pulp-web/templates/pulp-web.deployment.yaml.j2
  roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
  roles/redis/templates/redis.deployment.yaml.j2
Labels: lgtm, approved, do-not-merge/hold

#671 Add reconciliation logic to field update
  CHANGES/648.bugfix
  api/v1alpha1/pulp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
  controllers/pulp/api.go
  controllers/pulp/controller.go
  controllers/pulp/route.go
  controllers/pulp/status.go
  controllers/pulp/suite_test.go
  controllers/pulp/utils.go
  controllers/pulp/web.go
Labels: lgtm, approved

#658 Add validation webhook to handle field removal
  .github/workflows/ci.yml
  PROJECT
  api/v1alpha1/pulp_webhook.go
  api/v1alpha1/webhook_suite_test.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/rbac/role.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/pulp/controller.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved

#680 Fix IPv6 issue
  roles/pulp-web/templates/pulp-web.configmap.yaml.j2
Labels: lgtm, approved

#685 Update manifests
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#687 Set admin_password_secret field immutable
  CHANGES/646.bugfix
  api/v1alpha1/pulp_types.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
  controllers/pulp/api.go
  controllers/pulp/controller.go
  controllers/pulp/status.go
  controllers/pulp/utils.go
Labels: lgtm, approved

#688 Add image_pull_secrets reconciliation logic
  CHANGES/646.bugfix
  controllers/pulp/controller.go
  controllers/pulp/rbac.go
Labels: lgtm, approved

#686 Ensure Nginx Ingress Controller is used when multiple controllers are…
  CHANGES/673.bugfix
  controllers/pulp/controller.go
  controllers/pulp/ingress.go
Labels: lgtm, approved

#690 Add mount_trusted_ca reconciliation logic
  CHANGES/646.bugfix
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/worker.go
Labels: lgtm, approved

#682 Fix broken links
  CHANGES/681.doc
  docs/configuring/cache.md
  docs/configuring/database.md
  docs/configuring/reverse_proxy.md
  docs/configuring/storage.md
Labels: lgtm, approved

#691 Remove unused scripts
  .ci/scripts/deploy.sh
  .ci/scripts/k3s-install.sh
  .ci/scripts/molecule.sh
  .ci/scripts/quay-push.sh
  .github/workflows/scripts/build_images.sh
  .github/workflows/scripts/test_images.sh
  down.sh
  requirements.yml
  template_config.yml
  up.sh
Labels: lgtm, approved

#696 Fix node_selector reconciliation logic
  CHANGES/646.bugfix
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/utils.go
  controllers/pulp/worker.go
Labels: lgtm, approved

#694 Add operator doc page in README.md
  README.md
Labels: lgtm, approved

#695 Upgrade sdk to 1.24.1
  .dockerignore
  Makefile
  bundle.Dockerfile
  bundle/manifests/pulp-operator-manager-config_v1_configmap.yaml
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/controller_manager_config.yaml
  config/manager/manager.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
Labels: lgtm, approved

#697 Fixed more resources reconciliation
  CHANGES/646.bugfix
  controllers/pulp/utils.go
Labels: lgtm, approved

#699 Fix pdb reconciliation logic
  CHANGES/646.bugfix
  controllers/pulp/pdb.go
Labels: lgtm, approved

#700 Fix strategy reconciliation logic
  CHANGES/646.bugfix
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/redis.go
  controllers/pulp/worker.go
Labels: lgtm, approved

#701 Add ingress test on CI
  .ci/scripts/pulp_tests.sh
  .github/workflows/ci.yml
  .github/workflows/scripts/show_logs.sh
  CHANGES/678.misc
  config/samples/simple.ingress.yaml
Labels: lgtm, approved

#702 Fix pulp-web deployment reconciliation
  controllers/pulp/web.go
Labels: lgtm, approved

#703 Set Cache.ExternalCacheSecret immutable
  CHANGES/646.bugfix
  api/v1alpha1/pulp_types.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
  controllers/pulp/controller.go
  controllers/pulp/status.go
  controllers/pulp/utils.go
Labels: lgtm, approved

#704 Renaming packages
  Makefile
  api/v1alpha1/repo_manager_backup_types.go
  api/v1alpha1/repo_manager_restore_types.go
  api/v1alpha1/repo_manager_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/backup/controller.go
  controllers/backup/cr.go
  controllers/backup/database.go
  controllers/backup/pulp_dir.go
  controllers/backup/secret.go
  controllers/backup/suite_test.go
  controllers/repo_manager/README.md
  controllers/repo_manager/api.go
  controllers/repo_manager/content.go
  controllers/repo_manager/controller.go
  controllers/repo_manager/controller_test.go
  controllers/repo_manager/database.go
  controllers/repo_manager/ingress.go
  controllers/repo_manager/pdb.go
  controllers/repo_manager/rbac.go
  controllers/repo_manager/redis.go
  controllers/repo_manager/route.go
  controllers/repo_manager/sso.go
  controllers/repo_manager/status.go
  controllers/repo_manager/suite_test.go
  controllers/repo_manager/utils.go
  controllers/repo_manager/web.go
  controllers/repo_manager/worker.go
  controllers/restore/controller.go
  controllers/restore/database.go
  controllers/restore/deploy.go
  controllers/restore/pulp_dir.go
  controllers/restore/secret.go
  controllers/restore/utils.go
  controllers/utils.go
  main.go
Labels: lgtm, approved

#705 Fix Cache.RedisPort field update/reconciliation
  CHANGES/646.bugfix
  api/v1alpha1/repo_manager_types.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/repo_manager/README.md
  controllers/repo_manager/redis.go
Labels: lgtm, approved

#706 route: Ensure route_host backward compatibility
  roles/common/tasks/main.yml
Labels: lgtm, approved

#708 Fix broken doc
  docs/pulp.md
Labels: lgtm, approved

#707 config/rbac: Add ingresses.config.openshift.io
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/rbac/cluster_role.yaml
  config/rbac/cluster_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  molecule/default/resources.yml
Labels: lgtm, approved

#710 Fix more redis resources reconciliation
  CHANGES/646.bugfix
  controllers/repo_manager/redis.go
Labels: lgtm, approved

#712 Allow inter-pod affinity/anti-affinity config
  CHANGES/434.feature
  api/v1alpha1/repo_manager_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  controllers/repo_manager/README.md
  controllers/repo_manager/api.go
  controllers/repo_manager/content.go
  controllers/repo_manager/database.go
  controllers/repo_manager/redis.go
  controllers/repo_manager/utils.go
  controllers/repo_manager/worker.go
Labels: lgtm, approved

#713 Add command to rename kind
  .ci/scripts/backup_and_restore.sh
  .ci/scripts/kubelinter.sh
  .ci/scripts/local.sh
  .github/workflows/ci.yml
  .github/workflows/scripts/show_logs.sh
  CHANGES/692.misc
  Makefile
  controllers/utils.go
Labels: lgtm, approved

#715 Fix "spamming" retry in case of error
  CHANGES/650.bugfix
  controllers/repo_manager/utils.go
Labels: lgtm, approved

#718 Add ingressclass clusterrole
  CHANGES/709.bugfix
  config/rbac/role.yaml
  controllers/repo_manager/controller.go
Labels: lgtm, approved

#698 Utilize the renamed `pulp-minimal` and
  CHANGES/717.feature
  Makefile
  api/v1alpha1/repo_manager_types.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/manager/manager.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  config/samples/galaxy.azure.ci.yaml
  config/samples/galaxy.s3.ci.yaml
  config/samples/galaxy.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
  config/samples/simple-external-cache.yaml
  config/samples/simple-external-db.yaml
  config/samples/simple-sso.yaml
  config/samples/simple.ingress.yaml
  config/samples/simple.yaml
  controllers/repo_manager/api.go
  controllers/repo_manager/content.go
  controllers/repo_manager/controller_test.go
  controllers/repo_manager/worker.go
Labels: lgtm, approved

#723 Add a field to set operator unmanaged
  api/v1alpha1/repo_manager_types.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/repo_manager/README.md
  controllers/repo_manager/controller.go
Labels: lgtm, approved

#725 Upgrade: operator-sdk v1.25.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/rbac/role.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  go.mod
  go.sum
Labels: lgtm, approved

#727 Remove cache resources with CR update
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/repo_manager/README.md
  controllers/repo_manager/controller.go
  controllers/repo_manager/redis.go
Labels: lgtm, approved

#724 Add architecture doc section
  docs/architecture.md
  docs/images/pulp_architecture.png
  mkdocs.yml
Labels: lgtm, approved

#726 Fix testing the s6 pulp/pulp images
  .github/workflows/ci.yml
  .github/workflows/pr.yml
  config/samples/pulpproject_v1beta1_pulp_cr.s6.ci.yaml
  up.sh
Labels: approved

#730 Omit nginx configs from Pulp CR
  CHANGES/722.feature
  api/v1alpha1/repo_manager_types.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/repo_manager/ingress.go
  controllers/repo_manager/route.go
Labels: lgtm, approved

#731 Ensure ingress status conditions
  CHANGES/714.bugfix
  controllers/repo_manager/ingress.go
Labels: lgtm, approved

#732 Add goroutines for routes provisioning
  CHANGES/729.feature
  controllers/repo_manager/route.go
Labels: lgtm, approved
