Repository pulp/pulp-operator, pull requests merged in 2022-09, with the labels that each got.

#541 Configure service addresses based on ingressType
  controllers/pulp/api.go
Labels: lgtm, approved, go-beta

#540 Update docs for go based operator
  .github/workflows/ci.yml
  README.md
  docs/container.md
  docs/contributing.md
  docs/quickstart.md
  docs/roles/backup.md
  docs/roles/common.md
  docs/roles/postgres.md
  docs/roles/pulp-api.md
  docs/roles/pulp-content.md
  docs/roles/pulp-resource-manager.md
  docs/roles/pulp-routes.md
  docs/roles/pulp-status.md
  docs/roles/pulp-web.md
  docs/roles/pulp-worker.md
  docs/roles/redis.md
  docs/roles/restore.md
  mkdocs.yml
Labels: lgtm, approved, go-beta

#555 Fix S3 config
  controllers/pulp/api.go
Labels: lgtm, approved, go-beta

#553 Dev mode logs to be enabled with env vars
  .ci/scripts/local.sh
  main.go
Labels: lgtm, approved, go-beta

#558 Fix OCP image
  .ci/prow/Dockerfile.ci-operator
Labels: lgtm, approved

#556 Change logging style
  .ci/scripts/backup_and_restore.sh
  .github/workflows/scripts/show_logs.sh
  go.mod
  go.sum
  main.go
Labels: lgtm, approved

#557 Route workaround for rewrite case
  containers/images/pulp/container-assets/route_paths.py
Labels: lgtm, approved

#562 Adding NodeSelector/Toleration to Redis Deployment
  CHANGES/561.bugfix
  roles/redis/templates/redis.deployment.yaml.j2
Labels: lgtm, approved

#563 Improving log
  controllers/backup/controller.go
  controllers/backup/cr.go
  controllers/backup/database.go
  controllers/backup/pulp_dir.go
  controllers/backup/secret.go
  controllers/pulp/controller.go
  controllers/pulp/sso.go
  controllers/pulp/suite_test.go
  controllers/restore/controller.go
  controllers/restore/deploy.go
  controllers/restore/pulp_dir.go
  controllers/restore/secret.go
  main.go
Labels: lgtm, approved

#565 Add support for pulp_container signing service
  .ci/assets/kubernetes/signing_scripts.configmap.yaml
  CHANGES/564.feature
  containers/images/pulp/Containerfile.core.j2
  containers/images/pulp/container-assets/pulp-api
  playbooks/pulp.yml
  roles/pulp-api/templates/pulp-api.deployment.yaml.j2
Labels: lgtm, approved

#568 Fix typo on route
  containers/images/pulp/container-assets/route_paths.py
Labels: lgtm, approved

#569 Fix galaxy image
  .ci/ansible/galaxy/vars.yaml
Labels: lgtm, approved

#567 Go: Add support for pulp_container signing service
  .ci/assets/kubernetes/signing_scripts.configmap.yaml
  containers/images/pulp/Containerfile.core.j2
  containers/images/pulp/container-assets/pulp-api
  controllers/pulp/api.go
  controllers/pulp/utils.go
Labels: lgtm, approved, go-beta

#570 Improving go-based docs
  Makefile
  README.md
  controllers/backup/README.md
  controllers/pulp/README.md
  controllers/restore/README.md
  docs/backup.md
  docs/container.md
  docs/contributing.md
  docs/pulp.md
  docs/restore.md
Labels: lgtm, approved

#575 Fix wrong var attribution
  controllers/restore/deploy.go
Labels: lgtm, approved

#576 Go: Add app specific ServiceAccount
  api/v1alpha1/pulp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/pulp/README.md
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/controller.go
  controllers/pulp/controller_test.go
  controllers/pulp/database.go
  controllers/pulp/rbac.go
  controllers/pulp/redis.go
  controllers/pulp/web.go
  controllers/pulp/worker.go
  controllers/restore/utils.go
  go.mod
  go.sum
Labels: lgtm, approved

#573 Remove networkpolicy from default deploy step
  config/rbac/kustomization.yaml
  config/rbac/network_policy.yaml
Labels: lgtm, approved

#584 fix(docs): quickstart file path typo
  docs/quickstart.md
Labels: lgtm, needs-ok-to-test

#583 Fix issue with signing secret backup
  CHANGES/581.bugfix
  controllers/backup/secret.go
Labels: lgtm, approved

#582 Allow to control the restore deployment replicas
  CHANGES/572.feature
  api/v1alpha1/pulprestore_types.go
  controllers/restore/deploy.go
Labels: lgtm, approved

#587 Add probe fields in pulp CR
  CHANGES/516.feature
  api/v1alpha1/pulp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/database.go
  controllers/pulp/redis.go
  controllers/pulp/web.go
  controllers/pulp/worker.go
Labels: lgtm, approved

#588 Update kanban workflow
  .github/workflows/kanban.yml
Labels: lgtm, approved

#589 Fix backup issue when a PVC is manually provided
  CHANGES/580.bugfix
  controllers/backup/controller.go
Labels: lgtm, approved

#591 Update go docs nightly
  .github/workflows/nightly.yml
Labels: lgtm, approved

#592 Add option to mount custom CA
  CHANGES/513.feature
  api/v1alpha1/pulp_types.go
  config/crd/bases/repo-manager.pulpproject.org_pulprestores.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/controller.go
  controllers/pulp/utils.go
  controllers/pulp/worker.go
  controllers/restore/README.md
  docs/customCA.md
  mkdocs.yml
Labels: lgtm, approved

#598 Enable container tests
  .ci/scripts/pulp_tests.sh
  config/samples/galaxy.azure.ci.yaml
  config/samples/galaxy.s3.ci.yaml
  config/samples/galaxy.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml
  config/samples/repo-manager_v1alpha1_pulp.yaml
  config/samples/simple-external-db.yaml
  config/samples/simple-sso.yaml
  config/samples/simple.yaml
Labels: lgtm, approved

#597 Add more node selector configuration
  CHANGES/577.feature
  api/v1alpha1/pulp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
  controllers/pulp/redis.go
  controllers/pulp/route.go
  controllers/pulp/web.go
  docs/podPlacement.md
  docs/routes.md
  mkdocs.yml
Labels: lgtm, approved

#595 Enable container tests
  .ci/scripts/pulp_tests.sh
  config/samples/pulpproject_v1beta1_pulp_cr.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.azure.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.s3.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml
Labels: lgtm, approved

#599 Add samples for Object Storage secret
  CHANGES/593.doc
  docs/storage.md
Labels: lgtm, approved

#603 Add readiness probe to pulp-web container
  CHANGES/579.feature
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/web.go
Labels: lgtm, approved

#604 Run collectstatic during image build
  containers/images/pulp/Containerfile.core.j2
  containers/images/pulp/container-assets/pulp-api
  controllers/pulp/api.go
Labels: lgtm, approved, go-beta

#606 Add FAQ doc section
  docs/faq.md
  mkdocs.yml
Labels: lgtm, approved

#594 Run collectstatic during image build
  CHANGES/590.misc
  containers/images/pulp/Containerfile.core.j2
  containers/images/pulp/container-assets/pulp-api
  playbooks/pulp.yml
Labels: lgtm, approved

#602 Add serviceaccounts permission
  CHANGES/601.bugfix
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulprestores.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/pulp/controller.go
Labels: lgtm, approved

#607 Update example CR + update the bundle
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/samples/repo-manager_v1alpha1_pulp.yaml
Labels: lgtm, approved

#609 Take into account backup_pvc when removing owner references
  CHANGES/610.bugfix
  roles/backup/tasks/init.yml
Labels: lgtm, approved, ok-to-test

#616 Allow to configure PDB through Pulp CR
  CHANGES/433.feature
  api/v1alpha1/pulp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
  controllers/pulp/controller.go
  controllers/pulp/pdb.go
  docs/configuring/customCA.md
  docs/configuring/logLevel.md
  docs/configuring/pdb.md
  docs/configuring/podPlacement.md
  docs/configuring/routes.md
  docs/configuring/storage.md
  mkdocs.yml
Labels: lgtm, approved

#617 Stacktrace enabled only for above "panic" level.
  CHANGES/605.doc
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  docs/configuring/logLevel.md
Labels: lgtm, approved

#620 Storage type as enum
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/pulp.pulpproject.org_pulprestores.yaml
  config/crd/bases/pulpproject_v1beta1_pulprestore_crd.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#621 Fix .status.condition not reflecting real state
  CHANGES/600.bugfix
  config/rbac/role.yaml
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/controller.go
  controllers/pulp/database.go
  controllers/pulp/rbac.go
  controllers/pulp/route.go
  controllers/pulp/status.go
  controllers/pulp/utils.go
  controllers/pulp/web.go
  controllers/pulp/worker.go
  docs/tshoot/install.md
Labels: lgtm, approved

#623 Added documentation to config database
  CHANGES/619.doc
  api/v1alpha1/pulp_types.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/samples/simple-external-db.yaml
  controllers/pulp/README.md
  docs/configuring/database.md
  mkdocs.yml
Labels: lgtm, approved

#626 Use images from pulp-oci-images
  .ci/ansible/galaxy/vars.yaml
  .ci/ansible/galaxy/web/vars.yaml
  .ci/ansible/pulp/vars.yaml
  .ci/ansible/pulp/web/vars.yaml
  .ci/scripts/images.py
  .github/workflows/pulp_images.yml
  containers/README.md
  containers/ansible.cfg
  containers/build.yaml
  containers/common_tasks.yaml
  containers/compose/certs/database_fields.symmetric.key
  containers/compose/nginx/nginx.conf
  containers/compose/settings.py
  containers/images/pulp/Containerfile.core.j2
  containers/images/pulp/Containerfile.web.j2
  containers/images/pulp/container-assets/pulp-api
  containers/images/pulp/container-assets/pulp-common-entrypoint.sh
  containers/images/pulp/container-assets/pulp-content
  containers/images/pulp/container-assets/pulp-resource-manager
  containers/images/pulp/container-assets/pulp-worker
  containers/images/pulp/container-assets/readyz.py
  containers/images/pulp/container-assets/route_paths.py
  containers/images/pulp/container-assets/wait_on_database_migrations.sh
  containers/images/pulp/container-assets/wait_on_postgres.py
  containers/podman-compose.yml
  containers/push.yaml
  containers/vars/defaults.yaml
Labels: lgtm, approved

#615 Use images from pulp-oci-images
  .ci/ansible/galaxy/vars.yaml
  .ci/ansible/galaxy/web/vars.yaml
  .ci/ansible/pulp/vars.yaml
  .ci/ansible/pulp/web/vars.yaml
  .ci/scripts/images.py
  .github/workflows/pulp_images.yml
  containers/README.md
  containers/ansible.cfg
  containers/build.yaml
  containers/common_tasks.yaml
  containers/compose/certs/database_fields.symmetric.key
  containers/compose/nginx/nginx.conf
  containers/compose/settings.py
  containers/images/pulp/Containerfile.core.j2
  containers/images/pulp/Containerfile.web.j2
  containers/images/pulp/container-assets/pulp-api
  containers/images/pulp/container-assets/pulp-common-entrypoint.sh
  containers/images/pulp/container-assets/pulp-content
  containers/images/pulp/container-assets/pulp-resource-manager
  containers/images/pulp/container-assets/pulp-worker
  containers/images/pulp/container-assets/readyz.py
  containers/images/pulp/container-assets/route_paths.py
  containers/images/pulp/container-assets/wait_on_database_migrations.sh
  containers/images/pulp/container-assets/wait_on_postgres.py
  containers/podman-compose.yml
  containers/push.yaml
  containers/vars/defaults.yaml
Labels: lgtm, approved

#629 Remove some default db values
  CHANGES/622.bugfix
  api/v1alpha1/pulp_types.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
Labels: lgtm, approved

#628 Remove image leftovers
  .ci/scripts/deploy.sh
  .github/workflows/ci.yml
  .github/workflows/scripts/build_images.sh
  .github/workflows/scripts/test_images.sh
Labels: lgtm, approved

#633 Gather info to connect to external db from secrets
  CHANGES/630.feature
  api/v1alpha1/pulp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/samples/simple-external-db.yaml
  controllers/pulp/README.md
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/controller.go
  controllers/pulp/controller_test.go
  controllers/pulp/worker.go
  docs/configuring/database.md
Labels: lgtm, approved

#637 Modify the UID that runs the container process
  CHANGES/627.feature
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/web.go
  controllers/pulp/worker.go
Labels: lgtm, approved

#638 Minor fix for nodeSelector and affinity check
  api/v1alpha1/pulp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
  controllers/pulp/content.go
  controllers/pulp/redis.go
Labels: lgtm, approved

#639 Add some guidance on how PulpBackup should be used
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/pulp.pulpproject.org_pulpbackups.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
Labels: lgtm

#636 Add a field to configure the deployment strategy
  CHANGES/635.feature
  api/v1alpha1/pulp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/pulp/README.md
  controllers/pulp/api.go
  controllers/pulp/content.go
  controllers/pulp/redis.go
  controllers/pulp/worker.go
  docs/configuring/storage.md
  docs/faq.md
Labels: lgtm, approved

#634 Ensure CI logs
  .github/workflows/scripts/show_logs.sh
Labels: approved

#641 Fix deploy
  .github/workflows/ci.yml
Labels: lgtm, approved

#642 Modify the UID that runs the container process
  roles/pulp-api/templates/pulp-api.deployment.yaml.j2
  roles/pulp-content/templates/pulp-content.deployment.yaml.j2
  roles/pulp-resource-manager/templates/pulp-resource-manager.deployment.yaml.j2
  roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
Labels: lgtm, approved

#643 Update manifests
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#645 Remove default image values in spec to keep precedence order correct
  config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml
Labels: lgtm, approved
