Repository pulp/pulp-operator, pull requests merged in 2022-11, with the labels that each got.

#734 Check non-ocp env config with ingress_type:route
  CHANGES/669.feature
  controllers/repo_manager/controller.go
Labels: lgtm, approved

#740 Fix CI
  .ci/scripts/galaxy_ng-tests.sh
Labels: lgtm, approved

#741 Modify api and content svc to get clusterip
  CHANGES/737.bugfix
  controllers/repo_manager/api.go
  controllers/repo_manager/content.go
Labels: lgtm, approved, do-not-merge/hold

#745 Fix publishing operator image
  .github/workflows/ci.yml
Labels: lgtm, approved

#748 Update docs
  README.md
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#749 Fix some issues with pulp status
  .ci/scripts/backup_and_restore.sh
  CHANGES/735.bugfix
  CHANGES/736.bugfix
  controllers/repo_manager/controller.go
  controllers/repo_manager/controller_test.go
  controllers/repo_manager/route.go
  controllers/repo_manager/status.go
  controllers/repo_manager/utils.go
Labels: lgtm, approved

#750 Add demo option when filing issues
  .github/ISSUE_TEMPLATE/demo.md
  .github/ISSUE_TEMPLATE/task.md
Labels: lgtm, approved

#752 Modify controller RequeueAfter condition order
  CHANGES/747.bugfix
  controllers/repo_manager/controller.go
Labels: lgtm, approved

#754 Adding a "retry" in case it fails to update status
  CHANGES/751.bugfix
  controllers/repo_manager/status.go
Labels: lgtm, approved

#758 Fix ingress type assertion
  CHANGES/755.bugfix
  controllers/repo_manager/utils.go
Labels: lgtm, approved

#762 Fix an issue with wrong indentation
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, approved

#764 Enable multi-architecture builds from CI
  .github/workflows/ci.yml
  Makefile
Labels: lgtm, approved, needs-ok-to-test

#766 Add CI containerized scenario
  .github/workflows/ci.yml
  CHANGES/763.misc
Labels: lgtm, approved

#768 Added a control CM to avoid restore reconcile run
  CHANGES/550.feature
  controllers/restore/controller.go
  controllers/restore/utils.go
Labels: lgtm, approved

#772 Add missing full path to container images
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#774 Ensure full path
  config/manager/manager.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  controllers/backup/controller.go
  controllers/repo_manager/controller_test.go
  controllers/repo_manager/database.go
  controllers/repo_manager/redis.go
  controllers/restore/utils.go
Labels: lgtm, approved

#775 Add support for podman in Makefile
  Makefile
Labels: lgtm, approved

#776 Make route annotations editable
  api/v1alpha1/repo_manager_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  controllers/repo_manager/README.md
  controllers/repo_manager/route.go
Labels: lgtm, approved

#777 Refactor pulp-api provisioning method
  controllers/repo_manager/api.go
  controllers/repo_manager/utils.go
Labels: lgtm, approved

#778 Adding default readinessProbe for worker
  controllers/repo_manager/worker.go
Labels: lgtm, approved

#780 Add Ingress TLS secret
  CHANGES/676.feature
  api/v1alpha1/repo_manager_types.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  controllers/repo_manager/README.md
  controllers/repo_manager/ingress.go
Labels: lgtm, approved

#781 Refactor pulp-content provisioning method
  controllers/repo_manager/content.go
Labels: lgtm, approved

#783 Refactor pulp-worker provisioning method
  controllers/repo_manager/worker.go
Labels: lgtm, approved

#779 Make web available when ingress isn't nginx
  CHANGES/770.bugfix
  controllers/repo_manager/controller.go
Labels: lgtm, approved

#784 Create a random fernet key
  controllers/repo_manager/api.go
  controllers/repo_manager/utils.go
Labels: lgtm, approved

#787 Add needsRequeue func to controller
  controllers/repo_manager/controller.go
  controllers/repo_manager/utils.go
Labels: lgtm, approved

#789 Remove reconcileObject method repetitive blocks
  controllers/repo_manager/utils.go
Labels: lgtm, approved

#791 Add updateObject function
  controllers/repo_manager/api.go
  controllers/repo_manager/content.go
  controllers/repo_manager/ingress.go
  controllers/repo_manager/redis.go
  controllers/repo_manager/route.go
  controllers/repo_manager/utils.go
  controllers/repo_manager/web.go
  controllers/repo_manager/worker.go
Labels: lgtm, approved

#793 Upgrade SDK to 1.25.2
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
Labels: lgtm, approved

#795 Document unmanaged state process
  CHANGES/792.doc
  docs/configuring/unmanaged.md
  docs/faq.md
  mkdocs.yml
Labels: lgtm, approved

#798 pulp-api: remove secret_key fact
  roles/pulp-api/tasks/main.yml
Labels: lgtm, approved

#799 Remove pulp-web on upgrade with OCP route
  roles/pulp-routes/tasks/main.yml
Labels: lgtm, approved

#801 Add field to configure route custom cert
  CHANGES/800.feature
  api/v1alpha1/repo_manager_types.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  controllers/repo_manager/README.md
  controllers/repo_manager/route.go
  controllers/repo_manager/utils.go
  docs/configuring/routes.md
Labels: lgtm, approved

#769 Add a field to set IngressClass name
  CHANGES/674.feature
  api/v1alpha1/repo_manager_types.go
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/samples/simple.ingress.yaml
  controllers/repo_manager/README.md
  controllers/repo_manager/controller.go
  controllers/repo_manager/ingress.go
  controllers/repo_manager/status.go
  controllers/repo_manager/utils.go
  controllers/restore/deploy.go
  controllers/utils.go
  docs/configuring/reverse_proxy.md
Labels: lgtm, approved

#804 Fix a wrong validation to update .status field
  controllers/repo_manager/controller.go
Labels: lgtm, approved

#806 Update manifests
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#805 Add waitgroup to sync goroutines
  controllers/repo_manager/status.go
Labels: lgtm, approved

#803 Handle OCP Ingress
  controllers/repo_manager/controller.go
  controllers/repo_manager/ingress.go
  controllers/repo_manager/status.go
Labels: lgtm, approved

#809 Fix stalebot config
  .github/stale.yml
Labels: lgtm, approved

#810 Fix envtest evaluating wrong data
  CHANGES/807.bugfix
  controllers/repo_manager/controller_test.go
Labels: lgtm, approved

#812 Fix a permission/ownership error on bkp/restore
  CHANGES/808.bugfix
  controllers/backup/pulp_dir.go
  controllers/restore/pulp_dir.go
Labels: lgtm, approved

#813 Revert "config/rbac: Add ingresses.config.openshift.io"
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/rbac/cluster_role.yaml
  config/rbac/cluster_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  molecule/default/resources.yml
Labels: lgtm

#814 Refactor service reconciliation
  controllers/repo_manager/api.go
  controllers/repo_manager/content.go
  controllers/repo_manager/utils.go
Labels: lgtm, approved

#815 Add slack warning
  .github/workflows/ci.yml
Labels: lgtm, approved
