Repository pulp/pulp-operator, pull requests merged in 2023-04, with the labels that each got.

#926 Fix reconciliation and pipeline issues
  .ci/scripts/galaxy_ng-tests.sh
  .ci/scripts/pulp_tests.sh
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.azure.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.s3.ci.yaml
  roles/common/tasks/create_app_sa.yml
  roles/common/tasks/main.yml
  roles/postgres/tasks/main.yml
Labels: lgtm, approved

#927 Remove update task for operator SA
  roles/common/tasks/create_app_sa.yml
  roles/common/tasks/main.yml
Labels: approved

#936 Bump golang version and bind it with GH action
  .github/workflows/ci.yml
  CHANGES/935.misc
  Dockerfile
  Makefile
  go.mod
Labels: approved

#897 change date format to avoid ':'
  roles/backup/tasks/postgres.yml
Labels: lgtm, approved, needs-ok-to-test

#943 Add bundle-check to CI and update bundle files
  .ci/scripts/bundle_check.sh
  .github/workflows/ci.yml
  CHANGES/942.misc
  Makefile
  bundle/manifests/pulp-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
Labels: approved
