Repository pulp/pulp-operator, pull requests merged in 2023-07, with the labels that each got.

#996 [ansible] csv: Fix redis typo
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#998 Update tests to decrease liveness probe errors
  .github/workflows/ci.yml
  .github/workflows/scripts/show_logs.sh
  CHANGES/993.misc
  controllers/repo_manager/api.go
  controllers/repo_manager/controller_test.go
  main.go
Labels: approved

#999 Update date format on backup dirs
  CHANGES/937.bugfix
  controllers/backup/controller.go
  main.go
Labels: approved

#1002 Add an initContainer to register the gpg keys
  .ci/scripts/signing_metadata.sh
  .github/workflows/ci.yml
  CHANGES/1001.bugfix
  roles/pulp-api/defaults/main.yml
  roles/pulp-api/tasks/main.yml
  roles/pulp-api/tasks/signing_service.yml
  roles/pulp-api/templates/pulp-api.deployment.yaml.j2
  roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
Labels: lgtm, approved

#1004 Rename RELATED_IMAGE_ for GPG init container
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  roles/pulp-api/tasks/signing_service.yml
Labels: lgtm, approved

#1005 Move ocp resources to a different package
  CHANGES/884.misc
  controllers/deployment.go
  controllers/ingress.go
  controllers/ocp/deployment.go
  controllers/ocp/ingress.go
  controllers/ocp/route.go
  controllers/ocp/utils.go
  controllers/repo_manager/api.go
  controllers/repo_manager/content.go
  controllers/repo_manager/controller.go
  controllers/repo_manager/controller_test.go
  controllers/repo_manager/database.go
  controllers/repo_manager/deployment.go
  controllers/repo_manager/galaxy.go
  controllers/repo_manager/ingress.go
  controllers/repo_manager/ocp.go
  controllers/repo_manager/rbac.go
  controllers/repo_manager/redis.go
  controllers/repo_manager/sso.go
  controllers/repo_manager/status.go
  controllers/repo_manager/utils.go
  controllers/repo_manager/web.go
  controllers/repo_manager/worker.go
  controllers/utils.go
  main.go
Labels: lgtm, approved

#1013 Fulfill RFE to configure redis storage size
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/pulp.pulpproject.org_pulps.yaml
  config/crd/bases/pulpproject_v1beta1_pulp_crd.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  roles/redis/defaults/main.yml
  roles/redis/templates/redis.pvc.yaml.j2
Labels: lgtm, approved, needs-ok-to-test

#1020 Add redis_storage_size for ansible compatibility
  CHANGES/1016.feature
  apis/repo-manager.pulpproject.org/v1beta1/pulp_types.go
  apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/repo_manager/README.md
  controllers/repo_manager/redis.go
  main.go
Labels: approved

#1022 Allow resource definition for non-core containers
  CHANGES/1019.feature
  apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go
  apis/repo-manager.pulpproject.org/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  controllers/deployment.go
  controllers/repo_manager/README.md
  controllers/repo_manager/controller_test.go
  controllers/telemetry.go
  main.go
Labels: approved

#1023 Create indexerFunc to reduce code duplication
  controllers/repo_manager/controller.go
  controllers/repo_manager/utils.go
  main.go
Labels: approved
