Repository pulp/pulp-operator, pull requests merged in 2023-11, with the labels that each got.

#1131 Better organize Reconcile method tasks
  controllers/repo_manager/controller.go
  main.go
Labels: approved

#1134 Adds two-deployments job to GHA
  .github/workflows/ci.yml
  CHANGES/1100.misc
  config/samples/simple-test.yaml
  config/samples/simple-with-reduced-migration-cpu.yaml
Labels: lgtm, approved

#1135 Update GALAXY_FEATURE_FLAGS in controllers/repo_manager/secret.go
  controllers/repo_manager/secret.go
Labels: lgtm, approved, ok-to-test

#1137 Make addCustomPulpSettings function more "generic"
  .ci/scripts/kubelinter.sh
  CHANGES/1132.bugfix
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/samples/galaxy.azure.ci.yaml
  config/samples/galaxy.s3.ci.yaml
  config/samples/galaxy.yaml
  controllers/repo_manager/secret.go
  main.go
Labels: lgtm, approved

#1139 [noissue] Include ImagePullPolicy in initcontainers
  controllers/deployment.go
Labels: lgtm, approved, ok-to-test

#1141 Move k8s secrets tasks away from api.go
  controllers/repo_manager/api.go
  controllers/repo_manager/controller.go
  controllers/repo_manager/secret.go
  main.go
Labels: lgtm, approved

#1144 Move file storage tasks away from api.go
  controllers/repo_manager/api.go
  controllers/repo_manager/controller.go
  controllers/repo_manager/pvc.go
  main.go
Labels: lgtm, approved

#1151 Fix signing services
  .ci/assets/kubernetes/signing_scripts.yaml
  .github/workflows/ci.yml
  CHANGES/939.bugfix
  apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go
  apis/repo-manager.pulpproject.org/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  config/samples/galaxy.azure.ci.yaml
  config/samples/galaxy.s3.ci.yaml
  config/samples/galaxy.yaml
  controllers/backup/secret.go
  controllers/deployment.go
  controllers/repo_manager/README.md
  controllers/repo_manager/controller.go
  controllers/repo_manager/job.go
  controllers/repo_manager/precheck.go
  controllers/repo_manager/utils.go
  controllers/restore/secret.go
  controllers/settings/jobs.go
  controllers/utils.go
  main.go
Labels: lgtm, approved

#1153 Update doc index page
  CHANGES/1145.doc
  README.md
  docs/index.md
Labels: lgtm, approved

#1155 Add doc to configure the metadata signing
  CHANGES/1003.doc
  docs/configuring/metadata_signing.md
  mkdocs.yml
Labels: lgtm, approved

#1156 Remove code duplication for k8s job definition
  controllers/repo_manager/job.go
  main.go
Labels: lgtm, approved

#1157 Update pulp-server import from django-auth-ldap
  CHANGES/1154.bugfix
  controllers/repo_manager/ldap.go
  main.go
Labels: lgtm, approved

#1160 Add a pipeline job to test LDAP integration
  .ci/scripts/ldap_config.sh
  .ci/scripts/ldap_test.sh
  .github/workflows/ci.yml
  CHANGES/1124.misc
  config/samples/ldap.yaml
Labels: lgtm, approved
