Repository pulp/pulp-operator, pull requests merged in 2023-08, with the labels that each got.

#1024 Move reset admin password instructions to k8s jobs
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/deployment.go
  controllers/repo_manager/controller.go
  controllers/repo_manager/controller_test.go
  controllers/repo_manager/job.go
  controllers/utils.go
  docs/configuring/reset_admin_pwd.md
  go.mod
  go.sum
  main.go
  mkdocs.yml
Labels: approved

#1027 Fix external db backup
  roles/backup/tasks/postgres.yml
  roles/restore/tasks/postgres.yml
Labels: lgtm, approved, needs-ok-to-test

#1028 Use nodeport instead of port-forward in tests
  .ci/scripts/pulp_tests.sh
  .github/workflows/ci.yml
Labels: approved

#1030 [DOC] Fix path to the ingress.yaml sample
  docs/configuring/networking/reverse_proxy.md
Labels: approved

#1029 Create jobs to run migrations
  .github/workflows/scripts/show_logs.sh
  CHANGES/991.feature
  apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  controllers/deployment.go
  controllers/repo_manager/README.md
  controllers/repo_manager/content.go
  controllers/repo_manager/controller.go
  controllers/repo_manager/controller_test.go
  controllers/repo_manager/job.go
  controllers/repo_manager/status.go
  controllers/repo_manager/utils.go
  controllers/utils.go
  main.go
Labels: approved

#1035 Add initcontainers for pulpcore worker and content
  .ci/scripts/pulp_tests.sh
  .github/workflows/ci.yml
  .github/workflows/scripts/show_logs.sh
  apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go
  apis/repo-manager.pulpproject.org/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  config/samples/simple.yaml
  config/samples/telemetry.yaml
  controllers/deployment.go
  controllers/repo_manager/README.md
  controllers/repo_manager/api.go
  controllers/repo_manager/content.go
  controllers/repo_manager/controller_test.go
  controllers/repo_manager/job.go
  controllers/repo_manager/web.go
  main.go
Labels: approved

#1038 Add a precheck function to run validations
  controllers/repo_manager/controller.go
  controllers/repo_manager/precheck.go
  controllers/repo_manager/utils.go
  main.go
Labels: approved

#1039 Verify file_storage definition w/out storage_class
  .ci/scripts/galaxy_ng-tests.sh
  .github/workflows/ci.yml
  CHANGES/946.feature
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  config/samples/galaxy.azure.ci.yaml
  config/samples/galaxy.s3.ci.yaml
  config/samples/galaxy.yaml
  config/samples/repo-manager.pulpproject.org_v1beta2_pulp.yaml
  controllers/repo_manager/precheck.go
  main.go
Labels: approved

#1043 Update OCP pipeline sample CRs
  config/samples/pulpproject_v1beta1_pulp_cr.galaxy.ocp.ci.yaml
  config/samples/pulpproject_v1beta1_pulp_cr.ocp.ci.yaml
Labels: approved

#1050 Fixes bug related to CONTENT_ORIGIN scheme always being https
  CHANGES/1048.bugfix
  controllers/repo_manager/utils.go
Labels: lgtm, approved

#1049 Modify pulp resources reconciliation logic
  CHANGES/1041.misc
  controllers/deployment.go
  controllers/ocp/deployment.go
  controllers/ocp/ingress.go
  controllers/ocp/route.go
  controllers/repo_manager/api.go
  controllers/repo_manager/content.go
  controllers/repo_manager/ingress.go
  controllers/repo_manager/redis.go
  controllers/repo_manager/web.go
  controllers/repo_manager/worker.go
  controllers/utils.go
  main.go
Labels: approved

#1052 Add the `pulp_secret_key` field
  CHANGES/1040.feature
  apis/repo-manager.pulpproject.org/v1beta2/pulp_backup_types.go
  apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulpbackups.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  controllers/backup/README.md
  controllers/backup/controller.go
  controllers/backup/secret.go
  controllers/backup/utils.go
  controllers/repo_manager/README.md
  controllers/repo_manager/api.go
  controllers/repo_manager/controller.go
  controllers/repo_manager/precheck.go
  controllers/repo_manager/status.go
  controllers/repo_manager/utils.go
  controllers/restore/secret.go
  docs/configuring/secrets.md
  main.go
Labels: approved

#1054 [DOC] Add more info for manual ingress config
  docs/configuring/networking/reverse_proxy.md
Labels: approved

#1055 Update GH actions/setup-go to fix warning msgs
  .github/workflows/ci.yml
Labels: lgtm, approved

#1064 Update helm ci workflow to use the current source code
  .github/workflows/ci.yml
Labels: approved

#1068 Improve pulp secrets code organization
  controllers/repo_manager/api.go
  controllers/repo_manager/precheck.go
  controllers/repo_manager/secret.go
  controllers/repo_manager/sso.go
  controllers/repo_manager/utils.go
  main.go
Labels: approved

#1070 Add job to handle allowed_content_checksums update
  CHANGES/1060.feature
  apis/repo-manager.pulpproject.org/v1beta2/pulp_types.go
  apis/repo-manager.pulpproject.org/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/pulp-operator.clusterserviceversion.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/manifests/bases/pulp-operator.clusterserviceversion.yaml
  controllers/deployment.go
  controllers/repo_manager/README.md
  controllers/repo_manager/api.go
  controllers/repo_manager/controller.go
  controllers/repo_manager/job.go
  controllers/repo_manager/precheck.go
  controllers/repo_manager/secret.go
  controllers/repo_manager/status.go
  controllers/repo_manager/utils.go
  docs/configuring/content_checksums.md
  main.go
  mkdocs.yml
Labels: approved
