Repository pulp/pulp-operator, pull requests merged in 2024-08, with the labels that each got.

#1313 Bump controller-gen from v0.9.2 to v.0.14.0
  Dockerfile
  Makefile
  apis/repo-manager.pulpproject.org/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/repo-manager.pulpproject.org_pulpbackups.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulprestores.yaml
  bundle/manifests/repo-manager.pulpproject.org_pulps.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulpbackups.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulprestores.yaml
  config/crd/bases/repo-manager.pulpproject.org_pulps.yaml
  config/rbac/role.yaml
  go.mod
Labels: approved

#1314 Run tidy in lint job CI to update go.mod
  .github/workflows/ci.yml
Labels: approved

#1318 Fix CI errors
  .ci/scripts/backup_and_restore.sh
  .ci/scripts/pulp_ansible/distribution_repo.sh
  .ci/scripts/pulp_ansible/distribution_repo_version.sh
  .ci/scripts/pulp_ansible/quickstart.sh
  .ci/scripts/pulp_ansible/remote-collection-token.sh
  .ci/scripts/pulp_ansible/remote-collection.sh
  .ci/scripts/pulp_ansible/remote.sh
  .ci/scripts/pulp_ansible/repo.sh
  .ci/scripts/pulp_ansible/setup.sh
  .ci/scripts/pulp_ansible/sync-collection.sh
  .ci/scripts/pulp_ansible/sync.sh
  .ci/scripts/pulp_container/base.sh
  .ci/scripts/pulp_container/build_containerfile.sh
  .ci/scripts/pulp_container/cleanup_export.sh
  .ci/scripts/pulp_container/create_containerfile.sh
  .ci/scripts/pulp_container/create_example.sh
  .ci/scripts/pulp_container/distribution.sh
  .ci/scripts/pulp_container/docs_check.sh
  .ci/scripts/pulp_container/download_after_sync.sh
  .ci/scripts/pulp_container/download_after_tagging.sh
  .ci/scripts/pulp_container/export_repository.sh
  .ci/scripts/pulp_container/image_tagging.sh
  .ci/scripts/pulp_container/image_untagging.sh
  .ci/scripts/pulp_container/import_repository.sh
  .ci/scripts/pulp_container/manifest_copy.sh
  .ci/scripts/pulp_container/recursive_add_tag.sh
  .ci/scripts/pulp_container/recursive_remove_tag.sh
  .ci/scripts/pulp_container/remote.sh
  .ci/scripts/pulp_container/repo.sh
  .ci/scripts/pulp_container/second_repo.sh
  .ci/scripts/pulp_container/sync.sh
  .ci/scripts/pulp_container/tag_copy.sh
  .ci/scripts/pulp_tests.sh
  .github/workflows/ci.yml
  Dockerfile
  roles/pulp-api/templates/pulp-api.deployment.yaml.j2
Labels: approved

#1317 Add PodSecurityStandards to the web deployment and jobs
  .github/workflows/ci.yml
  CHANGES/1315.bugfix
  controllers/backup/controller.go
  controllers/deployment.go
  controllers/repo_manager/database.go
  controllers/repo_manager/job.go
  controllers/repo_manager/redis.go
  controllers/repo_manager/web.go
  controllers/restore/pulp_dir.go
  controllers/restore/utils.go
  controllers/telemetry.go
  controllers/utils.go
  go.mod
Labels: lgtm, approved, ok-to-test

#1316 Change apiVersion to avoid failure while deploying hub
  roles/postgres/tasks/main.yml
  roles/postgres/tasks/upgrade_postgres.yml
  roles/postgres/templates/postgres.yaml.j2
  roles/pulp-api/templates/pulp-api.deployment.yaml.j2
  roles/pulp-content/templates/pulp-content.deployment.yaml.j2
  roles/pulp-status/tasks/main.yml
  roles/pulp-web/templates/pulp-web.deployment.yaml.j2
  roles/pulp-worker/templates/pulp-worker.deployment.yaml.j2
  roles/redis/templates/redis.deployment.yaml.j2
Labels: lgtm, approved, needs-ok-to-test

#1320 Fix database/cache pods SCC error in OCP
  CHANGES/1319.bugfix
  controllers/repo_manager/database.go
  controllers/repo_manager/rbac.go
  controllers/repo_manager/redis.go
Labels: approved

#1324 Run reset-admin-password on reinstallation
  CHANGES/1294.bugfix
  controllers/repo_manager/job.go
  controllers/repo_manager/status.go
Labels: approved

#1329 Change apiVersion to avoid failure while deploying hub with HCO deployed
  roles/pulp-routes/tasks/main.yml
Labels: lgtm, approved, needs-ok-to-test

#1328 Enable IRSA for aws s3 backends
  CHANGES/1327.bugfix
  controllers/repo_manager/secret.go
Labels: lgtm, approved, ok-to-test
